services:
  - type: web
    name: RenfeEnjoyer-Backend
    env: python
    plan: free
    region: oregon
    buildCommand: bash setup.sh && pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true